WebPorfolioGenerator/Models/Post.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebPorfolioGenerator.Models
{
    [Table("Posts")]
    public class Post
    {
        [Key]
        public int PostId { get; set; }

        public int PortfolioId { get; set; }

        [StringLength(200)]
        public string Title { get; set; }

        [StringLength(200)]
        public string Subtitle { get; set; }
        
        public string Body { get; set; }
        
        public DateTime CreationDate { get; set; }

        public DateTime ModificationDate { get; set; }

    }
}

WebPorfolioGenerator/Controllers/AboutsController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebPorfolioGenerator.DAL;
using WebPorfolioGenerator.Models;

namespace WebPorfolioGenerator.Controllers
{
    public class AboutsController : Controller
    {
        private readonly WebPortfolioContext _context;

        public AboutsController(WebPortfolioContext context)
        {
            _context = context;
        }

        // GET: Abouts
        public async Task<IActionResult> Index()
        {
            return View(await _context.Abouts.ToListAsync());
        }

        public async Task<IActionResult> Preview(int? id)
        {
            About about = await _context.Abouts.SingleOrDefaultAsync(p => p.PortfolioId.Equals(id));
            Portfolio portfolio = await _context.Portfolios.SingleOrDefaultAsync(p => p.PortfolioId.Equals(id));
            Font font = await _context.Fonts.SingleOrDefaultAsync(p => p.Id.Equals(portfolio.FontId));

            ViewBag.FirstColor = portfolio.FirstColor;
            ViewBag.SecondColor = portfolio.SecondColor;

            ViewBag.FontName = font.FontName;
            ViewBag.FontFamily = font.FontFamily;
            ViewBag.Style = font.Style;
            ViewBag.Link = font.Link;

            ViewBag.Body = about != null ? about.Body ?? "" : "";
            ViewBag.Twitter = about != null ? about.Twitter ?? "" : "";
            ViewBag.Instagram = about != null ? about.Instagram ?? "" : "";
            ViewBag.Facebook = about != null ? about.Facebook ?? "" : "";
            ViewBag.Title = about != null ? about.Title ?? "" : "";

            return View(about);
        }

        // GET: Abouts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
                return NotFound();

            About about = await _context.Abouts.SingleOrDefaultAsync(m => m.AboutId == id);
            if (about == null)
                return NotFound();

            return View(about);
        }

        // GET: Abouts/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AboutId,PortfolioId,Title,Body,Twitter,Instagram,Facebook")] About about)
        {
            if (ModelState.IsValid)
            {
                _context.Add(about);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(about);
        }

        // GET: Abouts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();

            About about = await _context.Abouts.SingleOrDefaultAsync(m => m.AboutId == id);
            if (about == null)
                return NotFound();

            return View(about);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AboutId,PortfolioId,Title,Body,Twitter,Instagram,Facebook")] About about)
        {
            if (id != about.AboutId)
                return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(about);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AboutExists(about.AboutId))
                        return NotFound();
                    else
                        throw;
                }

                return RedirectToAction(nameof(Index));
            }
            return View(about);
        }

        // GET: Abouts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();

            About about = await _context.Abouts.SingleOrDefaultAsync(m => m.AboutId == id);
            if (about == null)
                return NotFound();

            return View(about);
        }

        // POST: Abouts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            About about = await _context.Abouts.SingleOrDefaultAsync(m => m.AboutId == id);
            _context.Abouts.Remove(about);

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AboutExists(int id)
        {
            return _context.Abouts.Any(e => e.AboutId == id);
        }
    }
}

WebPorfolioGenerator/Controllers/LocationsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;
using WebPorfolioGenerator.DAL;
using WebPorfolioGenerator.Models;

namespace WebPorfolioGenerator.Controllers
{
    public class LocationsController : Controller
    {
        private readonly WebPortfolioContext _context;

        public LocationsController(WebPortfolioContext context)
        {
            _context = context;
        }

        // GET: Locations
        public async Task<IActionResult> Index()
        {
            return View(await _context.Locations.ToListAsync());
        }

        public async Task<IActionResult> Preview(int? id)
        {
            if (id == null)
                return NotFound();

            Portfolio portfolio = await _context.Portfolios.SingleOrDefaultAsync(p => p.PortfolioId.Equals(id));

            ViewBag.FirstColor = portfolio.FirstColor;
            ViewBag.SecondColor = portfolio.SecondColor;

            Font font = await _context.Fonts.SingleOrDefaultAsync(p => p.Id.Equals(portfolio.FontId));

            ViewBag.FontName = font.FontName;
            ViewBag.FontFamily = font.FontFamily;
            ViewBag.Style = font.Style;
            ViewBag.Link = font.Link;

            return View(await _context.Locations.SingleOrDefaultAsync(m => m.PortfolioId == id));
        }

        // GET: Locations/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
                return NotFound();

            Location location = await _context.Locations.SingleOrDefaultAsync(m => m.IdLocation == id);
            if (location == null)
                return NotFound();

            return View(location);
        }

        // GET: Locations/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdLocation,Street,Latitude,Longitude,PostalCode,Email,PhoneNumber")] Location location)
        {
            if (ModelState.IsValid)
            {
                _context.Add(location);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(location);
        }

        // GET: Locations/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();

            Location location = await _context.Locations.SingleOrDefaultAsync(m => m.IdLocation == id);
            if (location == null)
                return NotFound();

            return View(location);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdLocation,Street,Latitude,Longitude,PostalCode,Email,PhoneNumber")] Location location)
        {
            if (id != location.IdLocation)
                return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(location);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LocationExists(location.IdLocation))
                        return NotFound();
                    else
                        throw;
                }
                return RedirectToAction(nameof(Index));
            }

            return View(location);
        }

        // GET: Locations/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();

            Location location = await _context.Locations.SingleOrDefaultAsync(m => m.IdLocation == id);
            if (location == null)
                return NotFound();

            return View(location);
        }

        // POST: Locations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            Location location = await _context.Locations.SingleOrDefaultAsync(m => m.IdLocation == id);
            _context.Locations.Remove(location);

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LocationExists(int id)
        {
            return _context.Locations.Any(e => e.IdLocation == id);
        }
    }
}

WebPorfolioGenerator/Controllers/PostsController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebPorfolioGenerator.DAL;
using WebPorfolioGenerator.Models;

namespace WebPorfolioGenerator.Controllers
{
    public class PostsController : Controller
    {
        private readonly WebPortfolioContext _context;

        public PostsController(WebPortfolioContext context)
        {
            _context = context;
        }

        // GET: Posts
        public async Task<IActionResult> Index(int? id)
        {
            return View(await _context.Posts.Where(p => p.PortfolioId.Equals(id)).ToListAsync());
        }

        public async Task<IActionResult> Preview(int? id)
        {
            if (id == null)
                return NotFound();

            Portfolio portfolio = await _context.Portfolios.SingleOrDefaultAsync(p => p.PortfolioId.Equals(id));

            ViewBag.FirstColor = portfolio.FirstColor;
            ViewBag.SecondColor = portfolio.SecondColor;

            Font font = await _context.Fonts.SingleOrDefaultAsync(p => p.Id.Equals(portfolio.FontId));

            ViewBag.FontName = font.FontName;
            ViewBag.FontFamily = font.FontFamily;
            ViewBag.Style = font.Style;
            ViewBag.Link = font.Link;

            return View(_context.Posts.Where(p => p.PortfolioId.Equals(id)).ToList());
        }

        // GET: Posts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
                return NotFound();

            Post post = await _context.Posts.SingleOrDefaultAsync(m => m.PostId == id);
            if (post == null)
                return NotFound();

            return View(post);
        }

        // GET: Posts/Create
        public IActionResult Create(int? id)
        {
            if (id == null)
                return NotFound();

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PostId,PortfolioId,Title,Subtitle,Body,CreationDate,ModificationDate")] Post post)
        {
            if (ModelState.IsValid)
            {
                _context.Add(post);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new { id = post.PortfolioId });
            }
            return View(post);
        }

        // GET: Posts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();

            Post post = await _context.Posts.SingleOrDefaultAsync(m => m.PostId == id);
            if (post == null)
                return NotFound();

            return View(post);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PostId,PortfolioId,Title,Subtitle,Body,CreationDate,ModificationDate")] Post post)
        {
            if (id != post.PostId)
                return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(post);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PostExists(post.PostId))
                        return NotFound();
                    else
                        throw;
                }

                return RedirectToAction(nameof(Index), new { id = post.PortfolioId });
            }

            return View(post);
        }

        // GET: Posts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();

            Post post = await _context.Posts.SingleOrDefaultAsync(m => m.PostId == id);
            if (post == null)
                return NotFound();

            return View(post);
        }

        // POST: Posts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            Post post = await _context.Posts.SingleOrDefaultAsync(m => m.PostId == id);
            _context.Posts.Remove(post);

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PostExists(int id)
        {
            return _context.Posts.Any(e => e.PostId == id);
        }
    }
}

WebPorfolioGenerator/Views/Posts/Create.cshtml
@model WebPorfolioGenerator.Models.Post
@{
    ViewData["Title"] = "Create";
    DateTime thisDay = DateTime.Today;
}
<h2>Create</h2>
<h4>Post</h4>
<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group col-md-6">
                <input type="hidden" asp-for="CreationDate" class="form-control" value="@thisDay.ToString("d")" />
                <input type="hidden" asp-for="PortfolioId" class="form-control" value="@ViewContext.RouteData.Values["id"]" />
            </div>
            <div class="form-group col-md-12">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group col-md-12">
                <label asp-for="Subtitle" class="control-label"></label>
                <input asp-for="Subtitle" class="form-control" />
                <span asp-validation-for="Subtitle" class="text-danger"></span>
            </div>
            <div class="form-group col-md-12">
                <label asp-for="Body" class="control-label"></label>
                <textarea data-provide="markdown" id="postBody" asp-for="Body" class="form-control"></textarea>
                <span asp-validation-for="Body" class="text-danger"></span>
            </div>
            <div class="form-group col-md-12 R">
                <a class="linkButton"asp-action="Index">Back to List</a>            
                <input type="submit" value="Create" class="btn btn-default linkButton" />
            </div>
        </form>
    </div>
</div>

WebPorfolioGenerator/Views/Posts/Delete.cshtml
@model WebPorfolioGenerator.Models.Post

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Post</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PortfolioId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PortfolioId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Subtitle)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Subtitle)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Body)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Body)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreationDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreationDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ModificationDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ModificationDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="PostId" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WebPorfolioGenerator/Views/Posts/Details.cshtml
@model WebPorfolioGenerator.Models.Post
@{
    ViewData["Title"] = "Details";
}
<h2>Details</h2>
<div>
    <h4>Post</h4>
    <hr />
    <div class="row">
        <div class="form-group col-md-12 R">
            @Html.DisplayNameFor(model => model.CreationDate) - @Html.DisplayFor(model => model.CreationDate)
        </div>
        <div class="form-group col-md-12 R">
            @Html.DisplayNameFor(model => model.ModificationDate) - @Html.DisplayFor(model => model.ModificationDate)
        </div>

        <div class="form-group col-md-12">
            <h1> @Html.DisplayFor(model => model.Title)</h1>
        </div>
        <div class="form-group col-md-12">
            <h2>  @Html.DisplayFor(model => model.Subtitle)</h2>
        </div>

        <div id="postBody" class="col-md-12">
            @Html.Raw(new HeyRed.MarkdownSharp.Markdown().Transform(Model.Body))
        </div>


    </div>
    <div class="row buttonContainer">
        <div class="col-md-12 R">
            <a class="linkButton" asp-action="Index" asp-route-id="@ViewContext.RouteData.Values["id"]">Back to List</a>
            <a class="linkButton" asp-action="Edit" asp-route-id="@Model.PostId">Edit</a>
        </div>
    </div>
</div>

WebPorfolioGenerator/Views/Posts/Edit.cshtml
@model WebPorfolioGenerator.Models.Post
@{
    ViewData["Title"] = "Edit";
    DateTime thisDay = DateTime.Today;
}
<h2>Edit</h2>
<h4>Post</h4>
<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="PostId" />
            <input type="hidden" asp-for="PortfolioId" class="form-control" />
            <input type="hidden" asp-for="CreationDate" class="form-control" />
            <input type="hidden" asp-for="ModificationDate" class="form-control" value="@thisDay.ToString("d")" />

            <div class="form-group col-md-12">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group col-md-12">
                <label asp-for="Subtitle" class="control-label"></label>
                <input asp-for="Subtitle" class="form-control" />
                <span asp-validation-for="Subtitle" class="text-danger"></span>
            </div>
            <div class="form-group col-md-12">
                <label asp-for="Body" class="control-label"></label>
                <textarea data-provide="markdown" id="postBody" asp-for="Body" class="form-control"></textarea>
                <span asp-validation-for="Body" class="text-danger"></span>
            </div>
                    
            <div class="row buttonContainer">
                <div class="col-md-12 R">
                    <a class="linkButton" asp-action="Index">Back to List</a>
                    <input type="submit" value="Save" class="btn btn-default linkButton" />
                </div>
            </div>
        </form>
    </div>
</div>

WebPorfolioGenerator/Views/Posts/Index.cshtml
@model IEnumerable<WebPorfolioGenerator.Models.Post>
@{
    ViewData["Title"] = "Index";
}
<h2>Index</h2>

<table class="table">
    <thead>
        <tr>
            <th>
                Creation date
            </th>
            <th>
                Post title
            </th>
            <th>
                Modification date
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CreationDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ModificationDate)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.PostId">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.PostId">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.PostId">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<div class="row buttonContainer">
    <div class="col-md-12 R">
        <a class="linkButton" asp-action="Create" asp-route-id="@ViewContext.RouteData.Values["id"]">Create New</a>
    </div>
</div>

WebPorfolioGenerator/Views/Posts/Preview.cshtml
@model IEnumerable<WebPorfolioGenerator.Models.Post>
@{
    Layout = null;
}

<link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
      asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
      asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
<link rel="stylesheet" href="~/css/site.min.css" />
<link rel="stylesheet" href="~/font-awesome/css/font-awesome.css" />
<link rel="stylesheet" href="~/toopay-bootstrap-markdown/css/bootstrap-markdown.min.css" />
<script src="~/lib/jquery/dist/jquery.js"></script>
<link href="@ViewBag.Link" rel="stylesheet">

<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1" style="background-color: @ViewBag.FirstColor; font-family: @ViewBag.FontName; font-style: @ViewBag.FontStyle;">
    <ul class="nav navbar-nav">
        <li><a style="color: @ViewBag.SecondColor;" asp-controller="Portfolios" asp-action="Preview" asp-route-id="@ViewContext.RouteData.Values["id"]">Home</a></li>
        <li><a style="color: @ViewBag.SecondColor" asp-controller="Posts" asp-action="Preview" asp-route-id="@ViewContext.RouteData.Values["id"]">Blog</a></li>
        <li><a style="color: @ViewBag.SecondColor" asp-controller="Abouts" asp-action="Preview" asp-route-id="@ViewContext.RouteData.Values["id"]">About</a></li>
        <li><a style="color: @ViewBag.SecondColor" asp-controller="Locations" asp-action="Preview" asp-route-id="@ViewContext.RouteData.Values["id"]">Location</a></li>
    </ul>
</div>
<div class="container" style="font-family: @ViewBag.FontName; font-style: @ViewBag.FontStyle;">

    @if (Model.Count() > 0)
    {
        foreach (var item in Model)
        {
            <div class="post">
                <div class="col-md-offset-2 col-md-10" style="color: @ViewBag.FirstColor;">
                    <h3>@Html.DisplayFor(modelItem => item.Title)</h3>
                </div>
                <div class="col-md-offset-2 col-md-10" style="color: @ViewBag.SecondColor;">
                    <h4>@Html.DisplayFor(modelItem => item.Subtitle)</h4>
                </div>
                <div class="col-md-offset-2 col-md-8 col-md-offset-2 R">
                    @Html.DisplayFor(modelItem => item.CreationDate)
                </div>
                <div class="col-md-offset-2 col-md-8 col-md-offset-2">
                    @Html.Raw(new HeyRed.MarkdownSharp.Markdown().Transform(item.Body))
                </div>
            </div>
        }
    }
    else
    {
        <div class="post">
            <div class="col-md-offset-2 col-md-10 C" style="color: @ViewBag.FirstColor;">
                <h3>NO POST</h3>
            </div>
        </div>
    }
</div>