WebPorfolioGenerator/Models/Portfolio.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebPorfolioGenerator.Models
{
    [Table("Portfolios")]
    public class Portfolio
    {
        [Key]
        public int PortfolioId { get; set; }

        public int UserId { get; set; }

        [StringLength(200)]
        public string PortfolioName { get; set; }

        [StringLength(200)]
        public string PortfolioSurname { get; set; }

        [StringLength(6)]
        public string ExtBackgroundImage { get; set; }

        [NotMapped]
        public string ImageName => PortfolioId + ExtBackgroundImage;

        [StringLength(8)]
        public string FirstColor { get; set; }

        [StringLength(8)]
        public string SecondColor { get; set; }

        public int FontId { get; set; }

    }
}

WebPorfolioGenerator/Controllers/AboutsController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebPorfolioGenerator.DAL;
using WebPorfolioGenerator.Models;

namespace WebPorfolioGenerator.Controllers
{
    public class AboutsController : Controller
    {
        private readonly WebPortfolioContext _context;

        public AboutsController(WebPortfolioContext context)
        {
            _context = context;
        }

        // GET: Abouts
        public async Task<IActionResult> Index()
        {
            return View(await _context.Abouts.ToListAsync());
        }

        public async Task<IActionResult> Preview(int? id)
        {
            About about = await _context.Abouts.SingleOrDefaultAsync(p => p.PortfolioId.Equals(id));
            Portfolio portfolio = await _context.Portfolios.SingleOrDefaultAsync(p => p.PortfolioId.Equals(id));
            Font font = await _context.Fonts.SingleOrDefaultAsync(p => p.Id.Equals(portfolio.FontId));

            ViewBag.FirstColor = portfolio.FirstColor;
            ViewBag.SecondColor = portfolio.SecondColor;

            ViewBag.FontName = font.FontName;
            ViewBag.FontFamily = font.FontFamily;
            ViewBag.Style = font.Style;
            ViewBag.Link = font.Link;

            ViewBag.Body = about != null ? about.Body ?? "" : "";
            ViewBag.Twitter = about != null ? about.Twitter ?? "" : "";
            ViewBag.Instagram = about != null ? about.Instagram ?? "" : "";
            ViewBag.Facebook = about != null ? about.Facebook ?? "" : "";
            ViewBag.Title = about != null ? about.Title ?? "" : "";

            return View(about);
        }

        // GET: Abouts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
                return NotFound();

            About about = await _context.Abouts.SingleOrDefaultAsync(m => m.AboutId == id);
            if (about == null)
                return NotFound();

            return View(about);
        }

        // GET: Abouts/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AboutId,PortfolioId,Title,Body,Twitter,Instagram,Facebook")] About about)
        {
            if (ModelState.IsValid)
            {
                _context.Add(about);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(about);
        }

        // GET: Abouts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();

            About about = await _context.Abouts.SingleOrDefaultAsync(m => m.AboutId == id);
            if (about == null)
                return NotFound();

            return View(about);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AboutId,PortfolioId,Title,Body,Twitter,Instagram,Facebook")] About about)
        {
            if (id != about.AboutId)
                return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(about);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AboutExists(about.AboutId))
                        return NotFound();
                    else
                        throw;
                }

                return RedirectToAction(nameof(Index));
            }
            return View(about);
        }

        // GET: Abouts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();

            About about = await _context.Abouts.SingleOrDefaultAsync(m => m.AboutId == id);
            if (about == null)
                return NotFound();

            return View(about);
        }

        // POST: Abouts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            About about = await _context.Abouts.SingleOrDefaultAsync(m => m.AboutId == id);
            _context.Abouts.Remove(about);

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AboutExists(int id)
        {
            return _context.Abouts.Any(e => e.AboutId == id);
        }
    }
}

WebPorfolioGenerator/Controllers/PortfoliosController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using WebPorfolioGenerator.DAL;
using WebPorfolioGenerator.Models;

namespace WebPorfolioGenerator.Controllers
{
    public class PortfoliosController : Controller
    {
        private readonly WebPortfolioContext _context;
        private readonly IHostingEnvironment _hostingEnvironment;

        public PortfoliosController(WebPortfolioContext context, IHostingEnvironment hostingEnvironment)
        {
            _context = context;
            _hostingEnvironment = hostingEnvironment;
        }

        // GET: Portfolios
        public async Task<IActionResult> Index(int? id)
        {
            List<Portfolio> modelo = new List<Portfolio>();
            int? userId = HttpContext.Session.GetInt32("UserId");
            int userRol = _context.Users.Where(u => u.UserId.Equals(userId)).Select(u => u.RolId).FirstOrDefault();

            if (userRol == 4)
                modelo = await _context.Portfolios.Where(n => n.UserId.Equals(userId)).ToListAsync();
            else if (id == null)
                modelo = await _context.Portfolios.ToListAsync();
            else
                modelo = await _context.Portfolios.Where(n => n.UserId.Equals(id)).ToListAsync();

            return View(modelo);
        }

        public async Task<IActionResult> Preview(int? id)
        {
            Portfolio portfolio = await _context.Portfolios.SingleOrDefaultAsync(p => p.PortfolioId.Equals(id));

            ViewBag.FirstColor = portfolio.FirstColor;
            ViewBag.SecondColor = portfolio.SecondColor;

            Font font = await _context.Fonts.SingleOrDefaultAsync(p => p.Id.Equals(portfolio.FontId));

            ViewBag.FontName = font.FontName;
            ViewBag.FontFamily = font.FontFamily;
            ViewBag.Style = font.Style;
            ViewBag.Link = font.Link;

            return View(portfolio);
        }

        // GET: Portfolios/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
                return NotFound();

            Portfolio portfolio = await _context.Portfolios.SingleOrDefaultAsync(m => m.PortfolioId == id);
            if (portfolio == null)
                return NotFound();

            return View(portfolio);
        }

        // GET: Portfolios/Create
        public IActionResult Create(int? id)
        {
            ViewBag.Fonts = _context.Fonts.ToList();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UserId,PortfolioId,PortfolioName,PortfolioSurname,FirstColor,SecondColor,FontId")] Portfolio portfolio, IFormFile image)
        {
            if (ModelState.IsValid)
            {
                if (image != null && image.Length > 0)
                    portfolio.ExtBackgroundImage = Path.GetExtension(image.FileName);

                _context.Add(portfolio);
                await _context.SaveChangesAsync();

                if (image != null && image.Length > 0)
                {
                    String path = Path.Combine(_hostingEnvironment.WebRootPath, "images", "backgrounds", portfolio.ImageName);

                    /* Read the File as byte[], just like a local File */
                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        await image.CopyToAsync(stream);
                    }
                }

                return RedirectToAction(nameof(Index), new { id = portfolio.UserId });
            }

            return View(portfolio);
        }

        // GET: Portfolios/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();

            Portfolio portfolio = await _context.Portfolios.SingleOrDefaultAsync(m => m.PortfolioId == id);
            if (portfolio == null)
                return NotFound();

            ViewBag.Fonts = _context.Fonts.ToList();

            return View(portfolio);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PortfolioId,PortfolioName,PortfolioSurname,FirstColor,SecondColor,FontId,ExtBackgroundImage,UserId")] Portfolio portfolio, IFormFile image)
        {
            if (id != portfolio.PortfolioId)
                return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    if (image != null && image.Length > 0)
                        portfolio.ExtBackgroundImage = Path.GetExtension(image.FileName);

                    _context.Update(portfolio);
                    await _context.SaveChangesAsync();

                    if (image != null && image.Length > 0)
                    {
                        String path = Path.Combine(_hostingEnvironment.WebRootPath, "images", "backgrounds", portfolio.ImageName);

                        /* Read the File as byte[], just like a local File */
                        using (var stream = new FileStream(path, FileMode.Create))
                        {
                            await image.CopyToAsync(stream);
                        }
                    }

                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PortfolioExists(portfolio.PortfolioId))
                        return NotFound();
                    else
                        throw;
                }

                return RedirectToAction(nameof(Index));
            }

            return View(portfolio);
        }

        // GET: Portfolios/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();

            Portfolio portfolio = await _context.Portfolios.SingleOrDefaultAsync(m => m.PortfolioId == id);
            if (portfolio == null)
                return NotFound();

            return View(portfolio);
        }

        // POST: Portfolios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            Portfolio portfolio = await _context.Portfolios.SingleOrDefaultAsync(m => m.PortfolioId == id);
            _context.Portfolios.Remove(portfolio);

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PortfolioExists(int id)
        {
            return _context.Portfolios.Any(e => e.PortfolioId == id);
        }
    }
}

WebPorfolioGenerator/Controllers/PostsController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebPorfolioGenerator.DAL;
using WebPorfolioGenerator.Models;

namespace WebPorfolioGenerator.Controllers
{
    public class PostsController : Controller
    {
        private readonly WebPortfolioContext _context;

        public PostsController(WebPortfolioContext context)
        {
            _context = context;
        }

        // GET: Posts
        public async Task<IActionResult> Index(int? id)
        {
            return View(await _context.Posts.Where(p => p.PortfolioId.Equals(id)).ToListAsync());
        }

        public async Task<IActionResult> Preview(int? id)
        {
            if (id == null)
                return NotFound();

            Portfolio portfolio = await _context.Portfolios.SingleOrDefaultAsync(p => p.PortfolioId.Equals(id));

            ViewBag.FirstColor = portfolio.FirstColor;
            ViewBag.SecondColor = portfolio.SecondColor;

            Font font = await _context.Fonts.SingleOrDefaultAsync(p => p.Id.Equals(portfolio.FontId));

            ViewBag.FontName = font.FontName;
            ViewBag.FontFamily = font.FontFamily;
            ViewBag.Style = font.Style;
            ViewBag.Link = font.Link;

            return View(_context.Posts.Where(p => p.PortfolioId.Equals(id)).ToList());
        }

        // GET: Posts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
                return NotFound();

            Post post = await _context.Posts.SingleOrDefaultAsync(m => m.PostId == id);
            if (post == null)
                return NotFound();

            return View(post);
        }

        // GET: Posts/Create
        public IActionResult Create(int? id)
        {
            if (id == null)
                return NotFound();

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PostId,PortfolioId,Title,Subtitle,Body,CreationDate,ModificationDate")] Post post)
        {
            if (ModelState.IsValid)
            {
                _context.Add(post);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new { id = post.PortfolioId });
            }
            return View(post);
        }

        // GET: Posts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();

            Post post = await _context.Posts.SingleOrDefaultAsync(m => m.PostId == id);
            if (post == null)
                return NotFound();

            return View(post);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PostId,PortfolioId,Title,Subtitle,Body,CreationDate,ModificationDate")] Post post)
        {
            if (id != post.PostId)
                return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(post);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PostExists(post.PostId))
                        return NotFound();
                    else
                        throw;
                }

                return RedirectToAction(nameof(Index), new { id = post.PortfolioId });
            }

            return View(post);
        }

        // GET: Posts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();

            Post post = await _context.Posts.SingleOrDefaultAsync(m => m.PostId == id);
            if (post == null)
                return NotFound();

            return View(post);
        }

        // POST: Posts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            Post post = await _context.Posts.SingleOrDefaultAsync(m => m.PostId == id);
            _context.Posts.Remove(post);

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PostExists(int id)
        {
            return _context.Posts.Any(e => e.PostId == id);
        }
    }
}

WebPorfolioGenerator/Views/Portfolios/Create.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
@model WebPorfolioGenerator.Models.Portfolio
@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>
<h4>Portfolio</h4>
<hr />

<div class="row">
    <div class="col-md-12">
        @{
            String routeId = (String)ViewContext.RouteData.Values["id"];
            String userId = !String.IsNullOrEmpty(routeId) && !routeId.Equals("0") ? routeId : HttpContextAccessor.HttpContext.Session.GetInt32("UserId").ToString();
        }
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="UserId" class="form-control col-md-6" value="@userId" />
            <div class="form-group col-md-6">
                <label asp-for="PortfolioName" class="control-label">Title</label>
                <input asp-for="PortfolioName" class="form-control" />
                <span asp-validation-for="PortfolioName" class="text-danger"></span>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="PortfolioSurname" class="control-label">Subtitle</label>
                <input asp-for="PortfolioSurname" class="form-control" />
                <span asp-validation-for="PortfolioSurname" class="text-danger"></span>
            </div>
            <div class="form-group col-md-6">
                <label class="control-label">Background image</label>
                <input type="file" name="image" id="image" class="form-control" />
            </div>
            <div class="form-group col-md-6">
                <label asp-for="FirstColor" class="control-label">First color</label>
                <input type="color" asp-for="FirstColor" class="form-control" />
                <span asp-validation-for="FirstColor" class="text-danger"></span>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="SecondColor" class="control-label">Second color</label>
                <input type="color" asp-for="SecondColor" class="form-control" />
                <span asp-validation-for="SecondColor" class="text-danger"></span>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="FontId" class="control-label">Font</label>
                <select asp-for="FontId" asp-items="@(new SelectList(@ViewBag.Fonts,"Id","FontName"))" class=" form-control"></select>
                <span asp-validation-for="FontId" class="text-danger"></span>
            </div>
            <div class="form-group col-md-12 R">
                <a class="linkButton" asp-action="Index">Back to List</a>
                <input type="submit" value="Create" class="btn btn-default linkButton" />
            </div>
        </form>
    </div>
</div>

WebPorfolioGenerator/Views/Portfolios/Delete.cshtml
@model WebPorfolioGenerator.Models.Portfolio
@{
    ViewData["Title"] = "Delete";
}
<h2>Delete</h2>
<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <div class="container">
        <div class="col-md-6 R">
            @Html.DisplayNameFor(model => model.PortfolioName)
        </div>
        <div class="col-md-6">
            <label>@Html.DisplayFor(model => model.PortfolioName)</label>
        </div>
        <div class="col-md-6 R">
            @Html.DisplayNameFor(model => model.PortfolioSurname)
        </div>
        <div class="col-md-6">
            <label>@Html.DisplayFor(model => model.PortfolioSurname)</label>
        </div>
        <div class="col-md-6 R">
            @Html.DisplayNameFor(model => model.FirstColor)
        </div>
        <div class="col-md-6">
            <label>@Html.DisplayFor(model => model.FirstColor)</label>
        </div>
        <div class="col-md-6 R">
            @Html.DisplayNameFor(model => model.SecondColor)
        </div>
        <div class="col-md-6">
            <label>@Html.DisplayFor(model => model.SecondColor)</label>
        </div>
        <div class="col-md-6 R">
            @Html.DisplayNameFor(model => model.FontId)
        </div>
        <div class="col-md-6">
            <label> @Html.DisplayFor(model => model.FontId)</label>
        </div>
    </div>
    <div class="row buttonContainer">
        <div class="col-md-12 R">
            <form asp-action="Delete">
                <a class="linkButton" asp-action="Index">Back to List</a>
                <input type="hidden" asp-for="PortfolioId" />
                <input class="linkButton" type="submit" value="Delete" class="btn btn-default" />
            </form>
        </div>
    </div>

</div>

WebPorfolioGenerator/Views/Portfolios/Details.cshtml
@model WebPorfolioGenerator.Models.Portfolio
@{
    ViewData["Title"] = "Details";
}
<h2>Details</h2>
<div>
    <h4>Portfolio</h4>
    <hr />
    <div class="container">
        <div class="col-md-6 R">
            @Html.DisplayNameFor(model => model.PortfolioName)
        </div>
        <div class="col-md-6">
            <label> @Html.DisplayFor(model => model.PortfolioName) </label>
        </div>
        <div class="col-md-6 R">
            @Html.DisplayNameFor(model => model.PortfolioSurname)
        </div>
        <div class="col-md-6">
            <label> @Html.DisplayFor(model => model.PortfolioSurname) </label>
        </div>
        <div class="col-md-6 R">
            @Html.DisplayNameFor(model => model.FirstColor)
        </div>
        <div class="col-md-6">
            <label> @Html.DisplayFor(model => model.FirstColor) </label>
        </div>
        <div class="col-md-6 R">
            @Html.DisplayNameFor(model => model.SecondColor)
        </div>
        <div class="col-md-6 ">
            <label> @Html.DisplayFor(model => model.SecondColor) </label>
        </div>
        <div class="col-md-6 R">
            @Html.DisplayNameFor(model => model.FontId)
        </div>
        <div class="col-md-6">
            <label> @Html.DisplayFor(model => model.FontId) </label>
        </div>
    </div>
</div>

<div class="row buttonContainer">
    <div class="col-md-12 R">
        <a class="linkButton" asp-action="Index">Back to List</a>
        <a class="linkButton" asp-action="Edit" asp-route-id="@Model.PortfolioId">Edit</a>
        <a class="linkButton" asp-controller="Posts" asp-action="Index" asp-route-id="@Model.PortfolioId">Post</a>
        <a class="linkButton" asp-controller="Locations" asp-action="Index" asp-route-id="@Model.PortfolioId">Localization</a>
        <a class="linkButton" asp-controller="Abouts" asp-action="Index" asp-route-id="@Model.PortfolioId">About me</a>
        <a class="linkButton" asp-action="Preview" asp-route-id="@Model.PortfolioId">Preview</a>
    </div>
</div>

WebPorfolioGenerator/Views/Portfolios/Edit.cshtml
@model WebPorfolioGenerator.Models.Portfolio
@{
    ViewData["Title"] = "Edit portfolio";
}
<h2>Edit</h2>
<h4>Portfolio</h4>
<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="PortfolioId" />
            <div class="form-group col-md-6">
                <label asp-for="PortfolioName" class="control-label">Title</label>
                <input asp-for="PortfolioName" class="form-control" />
                <span asp-validation-for="PortfolioName" class="text-danger"></span>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="PortfolioSurname" class="control-label">Subtitle</label>
                <input asp-for="PortfolioSurname" class="form-control" />
                <span asp-validation-for="PortfolioSurname" class="text-danger"></span>
            </div>
            <div class="form-group col-md-6">
                <label class="control-label">Background image</label>
                <input type="file" name="image" id="image" class="form-control" />
            </div>
            <div class="form-group col-md-6">
                <label asp-for="FirstColor" class="control-label">First color</label>
                <input type="color" asp-for="FirstColor" class="form-control" />
                <span asp-validation-for="FirstColor" class="text-danger"></span>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="SecondColor" class="control-label">Second color</label>
                <input type="color" asp-for="SecondColor" class="form-control" />
                <span asp-validation-for="SecondColor" class="text-danger"></span>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="FontId" class="control-label">Font</label>
                <select asp-for="FontId" asp-items="@(new SelectList(@ViewBag.Fonts,"Id","FontName"))" class=" form-control"></select>
                <span asp-validation-for="FontId" class="text-danger"></span>
            </div>
            <div class="form-group col-md-6" hidden="hidden">
                <input asp-for="ExtBackgroundImage" class="form-control" />
            </div>
            <div class="form-group col-md-6" hidden="hidden">
                <input asp-for="UserId" class="form-control" />
            </div>
            <div class="row buttonContainer">
                <div class="col-md-12 R">
                    <input class="linkButton" type="submit" value="Edit" class="btn btn-default" />
                </div>
            </div>
        </form>
    </div>
</div>

WebPorfolioGenerator/Views/Portfolios/Index.cshtml
@model IEnumerable<WebPorfolioGenerator.Models.Portfolio>
@{
    ViewData["Title"] = "Index";
}
<h2>Index</h2>

<table class="table">

    <thead>
        <tr>
            <th>
                Title
            </th>
            <th>
                Subtitle
            </th>
            <th>
                First color
            </th>
            <th>
                Second color
            </th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.PortfolioName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PortfolioSurname)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstColor)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SecondColor)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.PortfolioId">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.PortfolioId">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.PortfolioId">Delete</a>
                </td>
            </tr>
        }
    </tbody>

</table>

<div class="row buttonContainer">
    <div class="col-md-12 R">
        <a class="linkButton" asp-action="Create" asp-route-id="@ViewContext.RouteData.Values["id"]">Create</a>
    </div>
</div>

WebPorfolioGenerator/Views/Portfolios/Preview.cshtml
@model WebPorfolioGenerator.Models.Portfolio
@{
    ViewData["Title"] = "Details";
    Layout = null;
}

<link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
      asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
      asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
<link rel="stylesheet" href="~/css/site.min.css" />
<link rel="stylesheet" href="~/font-awesome/css/font-awesome.css" />
<link rel="stylesheet" href="~/toopay-bootstrap-markdown/css/bootstrap-markdown.min.css" />
<script src="~/lib/jquery/dist/jquery.js"></script>
<link href="@ViewBag.Link" rel="stylesheet">

<div style="background-image: url(/images/backgrounds/@Model.ImageName); font-family: @ViewBag.FontName; font-style: @ViewBag.FontStyle;">

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1" style="background-color: @Model.FirstColor">
        <ul class="nav navbar-nav">
            <li><a style="color: @Model.SecondColor;" asp-controller="Portfolios" asp-action="Preview" asp-route-id="@Model.PortfolioId">Home</a></li>
            <li><a style="color: @Model.SecondColor" asp-controller="Posts" asp-action="Preview" asp-route-id="@Model.PortfolioId">Blog</a></li>
            <li><a style="color: @Model.SecondColor" asp-controller="Abouts" asp-action="Preview" asp-route-id="@Model.PortfolioId">About</a></li>
            <li><a style="color: @Model.SecondColor" asp-controller="Locations" asp-action="Preview" asp-route-id="@Model.PortfolioId">Location</a></li>
        </ul>
    </div>

    <div id="titleBlog">
        <h1 style="color: @Model.FirstColor">@Html.DisplayFor(model => model.PortfolioName)</h1>
        <h2 style="color: @Model.SecondColor">@Html.DisplayFor(model => model.PortfolioSurname)</h2>
    </div>

    <input id="firstColor" hidden value="@Html.DisplayFor(model => model.FirstColor)" />
    <input id="secondColor" hidden value="@Html.DisplayFor(model => model.SecondColor)" />
    <input id="font" hidden value="@Html.DisplayFor(model => model.FontId)" />

</div>