WebPorfolioGenerator/Controllers/PortfoliosController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using WebPorfolioGenerator.DAL;
using WebPorfolioGenerator.Models;

namespace WebPorfolioGenerator.Controllers
{
    public class PortfoliosController : Controller
    {
        private readonly WebPortfolioContext _context;
        private readonly IHostingEnvironment _hostingEnvironment;

        public PortfoliosController(WebPortfolioContext context, IHostingEnvironment hostingEnvironment)
        {
            _context = context;
            _hostingEnvironment = hostingEnvironment;
        }

        // GET: Portfolios
        public async Task<IActionResult> Index(int? id)
        {
            List<Portfolio> modelo = new List<Portfolio>();
            int? userId = HttpContext.Session.GetInt32("UserId");
            int userRol = _context.Users.Where(u => u.UserId.Equals(userId)).Select(u => u.RolId).FirstOrDefault();

            if (userRol == 4)
                modelo = await _context.Portfolios.Where(n => n.UserId.Equals(userId)).ToListAsync();
            else if (id == null)
                modelo = await _context.Portfolios.ToListAsync();
            else
                modelo = await _context.Portfolios.Where(n => n.UserId.Equals(id)).ToListAsync();

            return View(modelo);
        }

        public async Task<IActionResult> Preview(int? id)
        {
            Portfolio portfolio = await _context.Portfolios.SingleOrDefaultAsync(p => p.PortfolioId.Equals(id));

            ViewBag.FirstColor = portfolio.FirstColor;
            ViewBag.SecondColor = portfolio.SecondColor;

            Font font = await _context.Fonts.SingleOrDefaultAsync(p => p.Id.Equals(portfolio.FontId));

            ViewBag.FontName = font.FontName;
            ViewBag.FontFamily = font.FontFamily;
            ViewBag.Style = font.Style;
            ViewBag.Link = font.Link;

            return View(portfolio);
        }

        // GET: Portfolios/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
                return NotFound();

            Portfolio portfolio = await _context.Portfolios.SingleOrDefaultAsync(m => m.PortfolioId == id);
            if (portfolio == null)
                return NotFound();

            return View(portfolio);
        }

        // GET: Portfolios/Create
        public IActionResult Create(int? id)
        {
            ViewBag.Fonts = _context.Fonts.ToList();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UserId,PortfolioId,PortfolioName,PortfolioSurname,FirstColor,SecondColor,FontId")] Portfolio portfolio, IFormFile image)
        {
            if (ModelState.IsValid)
            {
                if (image != null && image.Length > 0)
                    portfolio.ExtBackgroundImage = Path.GetExtension(image.FileName);

                _context.Add(portfolio);
                await _context.SaveChangesAsync();

                if (image != null && image.Length > 0)
                {
                    String path = Path.Combine(_hostingEnvironment.WebRootPath, "images", "backgrounds", portfolio.ImageName);

                    /* Read the File as byte[], just like a local File */
                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        await image.CopyToAsync(stream);
                    }
                }

                return RedirectToAction(nameof(Index), new { id = portfolio.UserId });
            }

            return View(portfolio);
        }

        // GET: Portfolios/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();

            Portfolio portfolio = await _context.Portfolios.SingleOrDefaultAsync(m => m.PortfolioId == id);
            if (portfolio == null)
                return NotFound();

            ViewBag.Fonts = _context.Fonts.ToList();

            return View(portfolio);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PortfolioId,PortfolioName,PortfolioSurname,FirstColor,SecondColor,FontId,ExtBackgroundImage,UserId")] Portfolio portfolio, IFormFile image)
        {
            if (id != portfolio.PortfolioId)
                return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    if (image != null && image.Length > 0)
                        portfolio.ExtBackgroundImage = Path.GetExtension(image.FileName);

                    _context.Update(portfolio);
                    await _context.SaveChangesAsync();

                    if (image != null && image.Length > 0)
                    {
                        String path = Path.Combine(_hostingEnvironment.WebRootPath, "images", "backgrounds", portfolio.ImageName);

                        /* Read the File as byte[], just like a local File */
                        using (var stream = new FileStream(path, FileMode.Create))
                        {
                            await image.CopyToAsync(stream);
                        }
                    }

                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PortfolioExists(portfolio.PortfolioId))
                        return NotFound();
                    else
                        throw;
                }

                return RedirectToAction(nameof(Index));
            }

            return View(portfolio);
        }

        // GET: Portfolios/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();

            Portfolio portfolio = await _context.Portfolios.SingleOrDefaultAsync(m => m.PortfolioId == id);
            if (portfolio == null)
                return NotFound();

            return View(portfolio);
        }

        // POST: Portfolios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            Portfolio portfolio = await _context.Portfolios.SingleOrDefaultAsync(m => m.PortfolioId == id);
            _context.Portfolios.Remove(portfolio);

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PortfolioExists(int id)
        {
            return _context.Portfolios.Any(e => e.PortfolioId == id);
        }
    }
}

WebPorfolioGenerator/Controllers/UsersController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebPorfolioGenerator.DAL;
using WebPorfolioGenerator.Models;

namespace WebPorfolioGenerator.Controllers
{
    public class UsersController : Controller
    {
        private readonly WebPortfolioContext _context;

        public UsersController(WebPortfolioContext context)
        {
            _context = context;
        }

        // GET: Users
        public async Task<IActionResult> Index()
        {
            int? userId = HttpContext.Session.GetInt32("UserId");
            int userRol = _context.Users.Where(u => u.UserId.Equals(userId)).Select(u => u.RolId).FirstOrDefault();
            List<User> model = new List<User>();

            switch (userRol)
            {
                case 1:
                    model = await _context.Users.ToListAsync();
                    break;
                case 2:
                    model = await _context.Users.Where(u => u.RolId == 2 || u.RolId == 4).ToListAsync();
                    break;
                case 3:
                    model = await _context.Users.Where(u => u.RolId == 2 || u.RolId == 3 || u.RolId == 4).ToListAsync();
                    break;
                case 4:
                    model = await _context.Users.Where(u => u.UserId.Equals(userId)).ToListAsync();
                    break;
            }

            return View(model);
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
                return NotFound();

            User user = await _context.Users.SingleOrDefaultAsync(m => m.UserId == id);
            if (user == null)
                return NotFound();

            return View(user);
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            ViewBag.Rols = _context.Rols.ToList();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UserId,UserName,Name,Surname,Password,RolId,Email,Birth,MovilePhone,Phone")] User user)
        {
            if (ModelState.IsValid)
            {
                _context.Add(user);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new { id = user.UserId });
            }
            return View(user);
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();

            User user = await _context.Users.SingleOrDefaultAsync(m => m.UserId == id);
            if (user == null)
                return NotFound();

            ViewBag.Rols = _context.Rols.ToList();

            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("UserId,UserName,Name,Surname,Password,RolId,Email,Birth,MovilePhone,Phone")] User user)
        {
            if (id != user.UserId)
                return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.UserId))
                        return NotFound();
                    else
                        throw;
                }

                return RedirectToAction(nameof(Index), new { id = id });
            }

            return View(user);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();

            User user = await _context.Users.SingleOrDefaultAsync(m => m.UserId == id);
            if (user == null)
                return NotFound();

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            User user = await _context.Users.SingleOrDefaultAsync(m => m.UserId == id);
            _context.Users.Remove(user);

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(int id)
        {
            return _context.Users.Any(e => e.UserId == id);
        }
    }
}

WebPorfolioGenerator/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebPorfolioGenerator</title>
    <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
          asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
          asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
    <link rel="stylesheet" href="~/css/site.min.css" />
    <link rel="stylesheet" href="~/font-awesome/css/font-awesome.css" />
    <link rel="stylesheet" href="~/toopay-bootstrap-markdown/css/bootstrap-markdown.min.css" />
    <script src="~/lib/jquery/dist/jquery.js"></script>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a id="logo" asp-area="" asp-controller="Users" asp-action="Index" class="navbar-brand">WPG.</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Users" asp-action="Index">User list</a></li>
                    <li><a asp-area="" asp-controller="Portfolios" asp-action="Index">Portfolio list</a></li>
                    <li class="navbar-header"><a asp-area="" asp-controller="Home" asp-action="Logout">Logout</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">

        @RenderBody()
        <br />
        <hr />
        <footer>
            <p>&copy; 2017 - WebPorfolioGenerator</p>
        </footer>
    </div>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
    </script>
    <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
            crossorigin="anonymous"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
    </script>
    <script src="~/js/site.min.js"></script>
    <script src="~/toopay-bootstrap-markdown/js/markdown.js"></script>
    <script src="~/toopay-bootstrap-markdown/js/bootstrap-markdown.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>